### ISSUE TITLE
[엔티티] 엔티티 수정

### ISSUE THREAD

**Issue by julia-heo** [ITTA-DIV/Div-Backend#12]
- [x]  @ManytoOne 인 요소에 JoinColumn 추가된 코드 수정
- [x] 수정된 필드 추가

**Comment by suucong** [comment]
오류 메시지 살펴보면 ManytoOne인 필드에 Column어노테이션을 추가해주기보다는 JoinColumn 어노테이션을 추가해주어야함! 내가 수정해서 develop에 반영함.
